import React, { useEffect, useRef, useState } from 'react';
import * as d3 from 'd3';
import Plotly from 'plotly.js';

interface ResearchFinding {
  id: string;
  title: string;
  content: string;
  statisticalData: {
    pValue: number;
    effectSize: number;
    confidenceInterval: [number, number];
    sampleSize: number;
    power: number;
  };
  literatureReferences: Array<{
    title: string;
    authors: string[];
    journal: string;
    year: number;
    relevance: number;
  }>;
  peerReviewScore: number;
  publicationReadiness: 'draft' | 'review' | 'ready';
}

interface ValidationMetric {
  name: string;
  value: number;
  threshold: number;
  status: 'pass' | 'warning' | 'fail';
}

const ResearchOutputStudio: React.FC = () => {
  const validationRef = useRef<HTMLDivElement>(null);
  const literatureRef = useRef<HTMLDivElement>(null);
  const reviewRef = useRef<HTMLDivElement>(null);
  const [selectedFinding, setSelectedFinding] = useState<ResearchFinding | null>(null);
  const [generatedReport, setGeneratedReport] = useState<string>('');

  const [researchFindings] = useState<ResearchFinding[]>([
    {
      id: 'rf1',
      title: 'Novel Biomarker Combination for Early Alzheimer\'s Detection',
      content: 'A combination of plasma amyloid-β42/40 ratio and phosphorylated tau shows superior diagnostic accuracy compared to individual biomarkers.',
      statisticalData: {
        pValue: 0.0001,
        effectSize: 1.8,
        confidenceInterval: [1.4, 2.2],
        sampleSize: 1200,
        power: 0.95
      },
      literatureReferences: [
        {
          title: 'Blood-based biomarkers for Alzheimer\'s disease',
          authors: ['Jack Jr, C.R.', 'Bennett, D.A.'],
          journal: 'Nature Reviews Neurology',
          year: 2023,
          relevance: 0.89
        },
        {
          title: 'Plasma phosphorylated tau181 as a biomarker',
          authors: ['Karikari, T.K.', 'Pascoal, T.A.'],
          journal: 'Nature Medicine',
          year: 2022,
          relevance: 0.92
        }
      ],
      peerReviewScore: 8.7,
      publicationReadiness: 'ready'
    },
    {
      id: 'rf2',
      title: 'Multi-Target Therapeutic Strategy Optimization',
      content: 'Simultaneous targeting of amyloid, tau, and neuroinflammation pathways yields 55% improvement in clinical outcomes.',
      statisticalData: {
        pValue: 0.001,
        effectSize: 1.2,
        confidenceInterval: [0.8, 1.6],
        sampleSize: 800,
        power: 0.88
      },
      literatureReferences: [
        {
          title: 'Multi-target drug design for Alzheimer\'s',
          authors: ['Cavalli, A.', 'Bolognesi, M.L.'],
          journal: 'Expert Opinion on Drug Discovery',
          year: 2024,
          relevance: 0.85
        }
      ],
      peerReviewScore: 7.9,
      publicationReadiness: 'review'
    }
  ]);

  // Initialize visualizations
  useEffect(() => {
    if (validationRef.current && selectedFinding) createValidationDashboard();
    if (literatureRef.current && selectedFinding) createLiteratureNetwork();
    if (reviewRef.current) createPeerReviewTimeline();
  }, [selectedFinding]);

  const generateAutomatedReport = (finding: ResearchFinding) => {
    const report = `# ${finding.title}

## Abstract
${finding.content}

## Methods
This study utilized advanced machine learning algorithms combined with causal inference methods to analyze biomarker data from ${finding.statisticalData.sampleSize} participants.

## Results

### Statistical Analysis
- **P-value**: ${finding.statisticalData.pValue}
- **Effect Size**: ${finding.statisticalData.effectSize.toFixed(2)} (95% CI: ${finding.statisticalData.confidenceInterval[0].toFixed(2)} - ${finding.statisticalData.confidenceInterval[1].toFixed(2)})
- **Sample Size**: ${finding.statisticalData.sampleSize}
- **Statistical Power**: ${(finding.statisticalData.power * 100).toFixed(1)}%

### Key Findings
${finding.content}

## Discussion

### Literature Context
${finding.literatureReferences.map(ref =>
  `- ${ref.authors.join(', ')} (${ref.year}). "${ref.title}". *${ref.journal}*. Relevance: ${(ref.relevance * 100).toFixed(1)}%`
).join('\n')}

### Implications
This finding represents a significant advancement in Alzheimer\'s research methodology, demonstrating the power of AI-driven causal inference approaches.

## Conclusion
The results support the hypothesis that ${finding.content.toLowerCase()}

---
*Generated by AlzNexus AI Research Platform*
*Peer Review Score: ${finding.peerReviewScore}/10*
*Publication Readiness: ${finding.publicationReadiness}*
`;

    setGeneratedReport(report);
  };

  const createValidationDashboard = () => {
    if (!validationRef.current || !selectedFinding) return;

    const metrics: ValidationMetric[] = [
      { name: 'P-value', value: selectedFinding.statisticalData.pValue, threshold: 0.05, status: selectedFinding.statisticalData.pValue < 0.05 ? 'pass' : 'fail' },
      { name: 'Effect Size', value: selectedFinding.statisticalData.effectSize, threshold: 0.8, status: selectedFinding.statisticalData.effectSize > 0.8 ? 'pass' : 'warning' },
      { name: 'Statistical Power', value: selectedFinding.statisticalData.power, threshold: 0.8, status: selectedFinding.statisticalData.power > 0.8 ? 'pass' : 'warning' },
      { name: 'Sample Size', value: selectedFinding.statisticalData.sampleSize, threshold: 100, status: selectedFinding.statisticalData.sampleSize > 100 ? 'pass' : 'fail' }
    ];

    const data = [{
      x: metrics.map(m => m.name),
      y: metrics.map(m => m.value),
      type: 'bar' as const,
      name: 'Metric Value',
      marker: {
        color: metrics.map(m =>
          m.status === 'pass' ? '#4CAF50' :
          m.status === 'warning' ? '#FF9800' : '#F44336'
        )
      }
    }];

    const layout = {
      title: 'Statistical Validation Dashboard',
      xaxis: { title: 'Metric' },
      yaxis: { title: 'Value' },
      showlegend: false,
      width: 600,
      height: 400,
      margin: { t: 50, r: 50, l: 60, b: 50 }
    };

    Plotly.newPlot(validationRef.current, data as any, layout as any);
  };

  const createLiteratureNetwork = () => {
    if (!literatureRef.current || !selectedFinding) return;

    const svg = d3.select(literatureRef.current);
    svg.selectAll('*').remove();

    const width = 600;
    const height = 300;
    const margin = { top: 20, right: 20, bottom: 60, left: 60 };

    svg.attr('width', width).attr('height', height);

    // Create literature connection network
    const nodes = [
      { id: 'current', label: 'Current Finding', x: 150, y: 150, type: 'current' },
      ...selectedFinding.literatureReferences.map((ref, index) => ({
        id: `ref${index}`,
        label: ref.title.substring(0, 30) + '...',
        x: 350 + (index % 2) * 100,
        y: 100 + (index * 50),
        type: 'reference',
        relevance: ref.relevance
      }))
    ];

    const links = selectedFinding.literatureReferences.map((_, index) => ({
      source: 'current',
      target: `ref${index}`,
      strength: selectedFinding.literatureReferences[index].relevance
    }));

    // Draw links
    svg.selectAll('.literature-link')
      .data(links)
      .enter()
      .append('line')
      .attr('class', 'literature-link')
      .attr('x1', d => nodes.find(n => n.id === d.source)!.x)
      .attr('y1', d => nodes.find(n => n.id === d.source)!.y)
      .attr('x2', d => nodes.find(n => n.id === d.target)!.x)
      .attr('y2', d => nodes.find(n => n.id === d.target)!.y)
      .attr('stroke', d => d.strength > 0.8 ? '#4CAF50' : d.strength > 0.6 ? '#FF9800' : '#F44336')
      .attr('stroke-width', d => d.strength * 5 + 2);

    // Draw nodes
    const nodeGroups = svg.selectAll('.literature-node')
      .data(nodes)
      .enter()
      .append('g')
      .attr('class', 'literature-node')
      .attr('transform', d => `translate(${d.x - 40}, ${d.y - 15})`);

    nodeGroups.append('rect')
      .attr('width', 80)
      .attr('height', 30)
      .attr('fill', d => d.type === 'current' ? '#2196F3' : '#9E9E9E')
      .attr('stroke', d => d.type === 'current' ? '#1976D2' : '#757575')
      .attr('rx', 3);

    nodeGroups.append('text')
      .attr('x', 40)
      .attr('y', 20)
      .attr('text-anchor', 'middle')
      .attr('fill', 'white')
      .attr('font-size', '9px')
      .text(d => d.label);
  };

  const createPeerReviewTimeline = () => {
    if (!reviewRef.current) return;

    const svg = d3.select(reviewRef.current);
    svg.selectAll('*').remove();

    const width = 600;
    const height = 200;
    const margin = { top: 20, right: 20, bottom: 40, left: 60 };

    svg.attr('width', width).attr('height', height);

    // Simulate peer review process
    const reviewStages = [
      { stage: 'Initial Review', score: 6.5, time: 0 },
      { stage: 'Statistical Validation', score: 7.2, time: 1 },
      { stage: 'Literature Integration', score: 8.1, time: 2 },
      { stage: 'Methodological Review', score: 8.7, time: 3 },
      { stage: 'Final Assessment', score: 8.7, time: 4 }
    ];

    const xScale = d3.scaleLinear()
      .domain([0, 4])
      .range([margin.left, width - margin.right]);

    const yScale = d3.scaleLinear()
      .domain([0, 10])
      .range([height - margin.bottom, margin.top]);

    // Add axes
    svg.append('g')
      .attr('transform', `translate(0,${height - margin.bottom})`)
      .call(d3.axisBottom(xScale).tickFormat(d => reviewStages[d as number]?.stage || ''));

    svg.append('g')
      .attr('transform', `translate(${margin.left},0)`)
      .call(d3.axisLeft(yScale).ticks(5));

    // Add review progression line
    const line = d3.line<{ time: number; score: number }>()
      .x(d => xScale(d.time))
      .y(d => yScale(d.score));

    svg.append('path')
      .datum(reviewStages)
      .attr('fill', 'none')
      .attr('stroke', '#4CAF50')
      .attr('stroke-width', 3)
      .attr('d', line);

    // Add score points
    svg.selectAll('.review-point')
      .data(reviewStages)
      .enter()
      .append('circle')
      .attr('class', 'review-point')
      .attr('cx', d => xScale(d.time))
      .attr('cy', d => yScale(d.score))
      .attr('r', 6)
      .attr('fill', '#4CAF50')
      .append('title')
      .text(d => `${d.stage}: ${d.score}/10`);
  };

  const exportReport = (format: 'pdf' | 'latex' | 'docx') => {
    // Simulate export functionality
    alert(`Exporting report as ${format.toUpperCase()}...\n\nThis would generate a publication-ready ${format} file with proper formatting, citations, and statistical tables.`);
  };

  return (
    <div className="p-6 bg-white rounded-lg shadow-lg">
      <h1 className="text-3xl font-bold text-gray-800 mb-6">Research Output Studio</h1>
      <p className="text-gray-600 mb-8">
        Transform AI-generated research insights into publication-ready scientific outputs.
        Automated report generation with statistical validation, literature integration, and peer review simulation.
      </p>

      {/* Research Findings Selection */}
      <div className="bg-gray-50 p-6 rounded-lg mb-8">
        <h2 className="text-xl font-semibold mb-4">Available Research Findings</h2>
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          {researchFindings.map(finding => (
            <div
              key={finding.id}
              className={`p-4 rounded-lg border cursor-pointer transition-all ${
                selectedFinding?.id === finding.id
                  ? 'border-blue-500 bg-blue-50'
                  : 'border-gray-200 hover:border-gray-300'
              }`}
              onClick={() => setSelectedFinding(finding)}
            >
              <h3 className="font-semibold text-gray-800 mb-2">{finding.title}</h3>
              <p className="text-sm text-gray-600 mb-3 line-clamp-2">{finding.content}</p>
              <div className="flex items-center justify-between text-sm">
                <span className={`px-2 py-1 rounded text-xs ${
                  finding.publicationReadiness === 'ready' ? 'bg-green-100 text-green-800' :
                  finding.publicationReadiness === 'review' ? 'bg-yellow-100 text-yellow-800' :
                  'bg-gray-100 text-gray-800'
                }`}>
                  {finding.publicationReadiness}
                </span>
                <span className="text-gray-500">Score: {finding.peerReviewScore}/10</span>
              </div>
            </div>
          ))}
        </div>
      </div>

      {selectedFinding && (
        <>
          {/* Statistical Validation Dashboard */}
          <div className="grid grid-cols-1 lg:grid-cols-2 gap-8 mb-8">
            <div className="bg-white p-4 rounded-lg border">
              <h2 className="text-xl font-semibold mb-4">Statistical Validation</h2>
              <div ref={validationRef} className="w-full h-80"></div>
              <div className="mt-4 grid grid-cols-2 gap-4 text-sm">
                <div className="flex items-center space-x-2">
                  <div className="w-4 h-4 bg-green-500 rounded"></div>
                  <span>Pass</span>
                </div>
                <div className="flex items-center space-x-2">
                  <div className="w-4 h-4 bg-yellow-500 rounded"></div>
                  <span>Warning</span>
                </div>
                <div className="flex items-center space-x-2">
                  <div className="w-4 h-4 bg-red-500 rounded"></div>
                  <span>Fail</span>
                </div>
              </div>
            </div>

            <div className="bg-white p-4 rounded-lg border">
              <h2 className="text-xl font-semibold mb-4">Literature Integration</h2>
              <div ref={literatureRef} className="w-full h-80"></div>
              <p className="text-sm text-gray-600 mt-2">
                Network showing connections to existing literature. Line thickness indicates relevance.
              </p>
            </div>
          </div>

          {/* Peer Review Simulator */}
          <div className="bg-white p-4 rounded-lg border mb-8">
            <h2 className="text-xl font-semibold mb-4">Peer Review Simulation</h2>
            <div ref={reviewRef} className="w-full h-60"></div>
            <div className="mt-4 bg-gray-50 p-4 rounded">
              <h3 className="font-semibold text-gray-700 mb-2">Current Assessment</h3>
              <div className="grid grid-cols-1 md:grid-cols-3 gap-4 text-sm">
                <div>
                  <span className="text-gray-600">Overall Score:</span>
                  <span className="font-bold text-green-600 ml-2">{selectedFinding.peerReviewScore}/10</span>
                </div>
                <div>
                  <span className="text-gray-600">Statistical Rigor:</span>
                  <span className="font-bold text-green-600 ml-2">Excellent</span>
                </div>
                <div>
                  <span className="text-gray-600">Novelty:</span>
                  <span className="font-bold text-blue-600 ml-2">High</span>
                </div>
              </div>
            </div>
          </div>

          {/* Automated Report Generation */}
          <div className="bg-gray-50 p-6 rounded-lg mb-8">
            <div className="flex justify-between items-center mb-4">
              <h2 className="text-xl font-semibold">Automated Report Generation</h2>
              <button
                onClick={() => generateAutomatedReport(selectedFinding)}
                className="px-6 py-2 bg-blue-500 text-white rounded-lg hover:bg-blue-600 transition-colors"
              >
                Generate Report
              </button>
            </div>

            {generatedReport && (
              <div className="bg-white p-4 rounded-lg border mb-4">
                <pre className="text-sm text-gray-800 whitespace-pre-wrap font-mono">
                  {generatedReport}
                </pre>
              </div>
            )}

            {/* Export Tools */}
            <div className="flex space-x-4">
              <button
                onClick={() => exportReport('pdf')}
                className="px-4 py-2 bg-red-500 text-white rounded hover:bg-red-600 transition-colors"
              >
                Export PDF
              </button>
              <button
                onClick={() => exportReport('latex')}
                className="px-4 py-2 bg-purple-500 text-white rounded hover:bg-purple-600 transition-colors"
              >
                Export LaTeX
              </button>
              <button
                onClick={() => exportReport('docx')}
                className="px-4 py-2 bg-green-500 text-white rounded hover:bg-green-600 transition-colors"
              >
                Export DOCX
              </button>
            </div>
          </div>
        </>
      )}

      {/* Publication Readiness Summary */}
      <div className="bg-blue-50 p-6 rounded-lg border-l-4 border-blue-500">
        <h2 className="text-xl font-semibold mb-4">Publication Readiness Assessment</h2>
        <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
          <div className="text-center">
            <div className="text-2xl font-bold text-green-600 mb-2">
              {researchFindings.filter(f => f.publicationReadiness === 'ready').length}
            </div>
            <div className="text-sm text-gray-600">Ready for Publication</div>
          </div>
          <div className="text-center">
            <div className="text-2xl font-bold text-yellow-600 mb-2">
              {researchFindings.filter(f => f.publicationReadiness === 'review').length}
            </div>
            <div className="text-sm text-gray-600">Needs Review</div>
          </div>
          <div className="text-center">
            <div className="text-2xl font-bold text-gray-600 mb-2">
              {researchFindings.filter(f => f.publicationReadiness === 'draft').length}
            </div>
            <div className="text-sm text-gray-600">Draft Stage</div>
          </div>
        </div>
        <p className="text-sm text-blue-700 mt-4">
          <strong>AI Research Excellence:</strong> Every finding includes statistical validation,
          literature integration, and peer review simulation - transforming AI outputs into
          publication-ready scientific contributions.
        </p>
      </div>
    </div>
  );
};

export default ResearchOutputStudio;